### ISSUE TITLE
Needs ENS support

### ISSUE THREAD

**Issue by mbeylin** [Bounties-Network/Explorer#233]
We should add ENS support to our application, such that any time an address is displayed on our UI, we instead display their ENS name (if they have one which resolves to that address). 

@villanuevawill Please share your thoughts on how we should implement this in the application (architecture wise)

@decanus we need to bounty this shit!

**Comment by villanuevawill** [comment]
Awesome - so for v1 - I think the best thing to do is reverse lookup.  Based on our discussion, we could have a script running every hour that checks users for a root ENS. If they have one, then we can add it to the user model.

The frontend avatar will just prioritize showing the ENS field vs. the address. This task will require work on our API and very little on the frontend code here.

**Comment by villanuevawill** [comment]
This spec belongs in our API. I'll @ both of you there with a description ready for bountying.
