### ISSUE TITLE
Explorer stuck on loading screen without MetaMask

### ISSUE THREAD

**Issue by stevemulligan** [Bounties-Network/Explorer#294]
I've tried in Chrome and Safari, both on MacOS.  When MetaMask extension is not installed, there is a loading screen that never goes away.  No errors, nor any pending network requests are seen in the browser console.

https://explorer.bounties.network

**Comment by villanuevawill** [comment]
@stevemulligan thanks - we pushed a breaking change recently. Fixing this now. Thanks for reporting this - 💯

**Comment by villanuevawill** [comment]
@stevemulligan this is now fixed.
